name: Python application

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download previous CSV (if exists)
      run: |
        mkdir -p data
        aws s3 cp s3://my-bucket/aum_data.csv ./data/aum_data.csv || echo "No previous CSV found."

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: |
        python webscraping_hkex_3etfs.py

    - name: Upload updated CSV
      uses: actions/upload-artifact@v3
      with:
        name: aum-data
        path: aum_data.csv
